const mainContent=document.getElementById('main'),waterQuality=document.getElementById('quality'),protection=document.getElementById('protect'),liveMonitoring=document.getElementById('monitoring'),waterDetective=document.getElementById('detective');
mainContent.insertBefore(liveMonitoring,protection);
mainContent.insertBefore(waterQuality,waterDetective);

const detectiveQuestions=[
 {q:'After a heavy rainstorm, a stream suddenly becomes much cloudier. What might have happened?',a:['Soil and sediment washed into the stream','The water suddenly became saltwater','The stream stopped flowing','Fish changed the color of the water'],correct:0,e:'Rainwater can carry soil and sediment from roads, lawns, construction areas, and stream banks into waterways, increasing turbidity.'},
 {q:'Why can very warm stream water sometimes be a problem?',a:['Warm water can affect aquatic organisms and dissolved oxygen','Warm water always removes pollution','Warm water prevents rainfall','Temperature never matters'],correct:0,e:'Water temperature affects aquatic organisms and can influence dissolved oxygen and other environmental conditions.'},
 {q:'Why should we measure water quality over time instead of only once?',a:['Water conditions can change after rain, seasons, pollution events, and other environmental changes','Sensors only work twice','Water never changes','One measurement explains everything'],correct:0,e:'Repeated measurements help reveal patterns and changes that a single snapshot cannot show.'}
];
const knowledgeQuestions=[
 {q:'What is one important job of wetlands?',a:['Filtering water','Producing plastic','Creating roads','Increasing pollution'],correct:0,e:'Wetland plants and soils can help filter water and capture sediment.'},
 {q:'Why is biodiversity important?',a:['Healthy ecosystems depend on many interacting species','Ecosystems only need one species','Biodiversity increases pollution','It has no effect'],correct:0,e:'Biodiversity connects species in food webs and helps ecosystems function.'},
 {q:'What can people do to help waterways?',a:['Reduce pollution and report environmental problems','Throw waste into streams','Pour chemicals into drains','Damage stream banks'],correct:0,e:'Thoughtful choices, observation, and community participation can all help protect waterways.'}
];

function createQuiz(rootId,questions,type){let index=0,score=0,answered=false;const root=document.getElementById(rootId);function render(){if(index>=questions.length){root.innerHTML=`<div class="result"><div class="result-score">${score}/${questions.length}</div><h3>${type==='detective'?'Great Swamp Water Detective!':'Wetland knowledge unlocked!'}</h3><p>${score===questions.length?'Excellent work—you followed every clue.':'Nice investigating. Review the clues and try again!'}</p><button class="button primary restart">Try again ↻</button></div>`;root.querySelector('.restart').onclick=()=>{index=0;score=0;answered=false;update();render()};update();return}const item=questions[index];root.innerHTML=`<span class="question-tag">${type==='detective'?'CASE FILE':'WETLAND QUIZ'} · ${String(index+1).padStart(2,'0')}</span><div class="question">${item.q}</div><div class="answers">${item.a.map((a,i)=>`<button class="answer" data-i="${i}"><b>${String.fromCharCode(65+i)}.</b> ${a}</button>`).join('')}</div><div class="feedback" role="status"></div><button class="button primary next-button">${index===questions.length-1?'See my score':'Next question'} →</button>`;root.querySelectorAll('.answer').forEach(btn=>btn.onclick=()=>choose(btn,item));root.querySelector('.next-button').onclick=()=>{index++;answered=false;update();render()};update()}function choose(btn,item){if(answered)return;answered=true;const chosen=+btn.dataset.i;if(chosen===item.correct){score++;btn.classList.add('correct')}else{btn.classList.add('wrong');root.querySelector(`[data-i="${item.correct}"]`).classList.add('correct')}root.querySelectorAll('.answer').forEach(b=>b.disabled=true);const feedback=root.querySelector('.feedback');feedback.innerHTML=`<strong>${chosen===item.correct?'Correct!':'Good try.'}</strong> ${item.e}`;feedback.classList.add('show');root.querySelector('.next-button').classList.add('show');update()}function update(){if(type==='detective'){document.getElementById('detective-number').textContent=Math.min(index+1,questions.length)}else{document.getElementById('quiz-label').textContent=index>=questions.length?'Quiz complete':`Question ${index+1} of ${questions.length}`;document.getElementById('quiz-score-label').textContent=`Score ${score}`;document.getElementById('quiz-bar').style.width=`${Math.min((index+1)/questions.length*100,100)}%`}}render()}

createQuiz('detective-game',detectiveQuestions,'detective');createQuiz('knowledge-game',knowledgeQuestions,'knowledge');
document.querySelectorAll('.learn-more').forEach(btn=>btn.addEventListener('click',()=>{const card=btn.closest('.quality-card');card.classList.toggle('open');btn.setAttribute('aria-expanded',card.classList.contains('open'))}));
const menu=document.querySelector('.menu-toggle'),links=document.querySelector('.nav-links');menu.addEventListener('click',()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',open)});links.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{links.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
document.getElementById('report-form').addEventListener('submit',e=>{e.preventDefault();const success=e.currentTarget.querySelector('.form-success');success.classList.add('show');e.currentTarget.querySelector('button[type="submit"]').textContent='Prototype demonstrated ✓'});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
